version: 3.8

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
      - "5678:5678"  # Debugging port
    volumes:
      - .:/app
      # Need SQLite database file to persist data, store in /data
      - ./data:/app/data

    # env_file:
    #   - .env

    # Run uvicorn command with --reload
    command: 