"""add_is_playoff_game_to_scheduled_games

Revision ID: 20a8f90c4c75
Revises: f378ca14303a
Create Date: 2025-07-28 13:01:11.126229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a8f90c4c75'
down_revision = 'f378ca14303a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_games', sa.Column('is_playoff_game', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_games', 'is_playoff_game')
    # ### end Alembic commands ###
