"""Add score fields to Game model

Revision ID: 48b56284cfab
Revises: fd0f8271073e
Create Date: 2025-05-26 01:19:43.808295

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48b56284cfab"
down_revision = "fd0f8271073e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("playing_team_score", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("opponent_team_score", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "opponent_team_score")
    op.drop_column("games", "playing_team_score")
    # ### end Alembic commands ###
