"""Add seasons table and season_id to games

Revision ID: 69cd99a5e5f6
Revises: b1e1ff107303
Create Date: 2025-05-30 15:37:49.095780

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "69cd99a5e5f6"
down_revision = "b1e1ff107303"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("end_date > start_date", name="season_dates_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index("idx_season_dates", "seasons", ["start_date", "end_date"], unique=False)
    op.add_column("games", sa.Column("season_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "games", "seasons", ["season_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "games", type_="foreignkey")
    op.drop_column("games", "season_id")
    op.drop_index("idx_season_dates", table_name="seasons")
    op.drop_table("seasons")
    # ### end Alembic commands ###
