"""Add season statistics tables

Revision ID: 6c1432a982da
Revises: 13bb0669f405
Create Date: 2025-05-23 01:45:21.317550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1432a982da'
down_revision = '13bb0669f405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('total_points_for', sa.Integer(), nullable=False),
    sa.Column('total_points_against', sa.Integer(), nullable=False),
    sa.Column('total_ftm', sa.Integer(), nullable=False),
    sa.Column('total_fta', sa.Integer(), nullable=False),
    sa.Column('total_2pm', sa.Integer(), nullable=False),
    sa.Column('total_2pa', sa.Integer(), nullable=False),
    sa.Column('total_3pm', sa.Integer(), nullable=False),
    sa.Column('total_3pa', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', name='uq_team_season')
    )
    op.create_table('player_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('total_fouls', sa.Integer(), nullable=False),
    sa.Column('total_ftm', sa.Integer(), nullable=False),
    sa.Column('total_fta', sa.Integer(), nullable=False),
    sa.Column('total_2pm', sa.Integer(), nullable=False),
    sa.Column('total_2pa', sa.Integer(), nullable=False),
    sa.Column('total_3pm', sa.Integer(), nullable=False),
    sa.Column('total_3pa', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_season')
    )
    op.alter_column('active_rosters', 'checked_in_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('active_rosters', 'is_starter',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_unique_constraint('uq_game_player', 'active_rosters', ['game_id', 'player_id'])
    op.alter_column('game_events', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('idx_game_events_game_id', table_name='game_events')
    op.drop_index('idx_game_events_timestamp', table_name='game_events')
    op.alter_column('game_states', 'home_timeouts_remaining',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'5'"))
    op.alter_column('game_states', 'away_timeouts_remaining',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'5'"))
    op.alter_column('game_states', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('game_states', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('games', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('players', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('games', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('game_states', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('game_states', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('game_states', 'away_timeouts_remaining',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'5'"))
    op.alter_column('game_states', 'home_timeouts_remaining',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'5'"))
    op.create_index('idx_game_events_timestamp', 'game_events', ['timestamp'], unique=False)
    op.create_index('idx_game_events_game_id', 'game_events', ['game_id'], unique=False)
    op.alter_column('game_events', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint('uq_game_player', 'active_rosters', type_='unique')
    op.alter_column('active_rosters', 'is_starter',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('active_rosters', 'checked_in_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_table('player_season_stats')
    op.drop_table('team_season_stats')
    # ### end Alembic commands ###
