"""Update database schema

Revision ID: 834c9663d23c
Revises: 
Create Date: 2025-05-19 14:55:12.156436

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '834c9663d23c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('playing_team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['playing_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'jersey_number', name='uq_player_team_jersey'),
    sa.UniqueConstraint('team_id', 'name', name='uq_player_team_name')
    )
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), nullable=False),
    sa.Column('total_ftm', sa.Integer(), nullable=False),
    sa.Column('total_fta', sa.Integer(), nullable=False),
    sa.Column('total_2pm', sa.Integer(), nullable=False),
    sa.Column('total_2pa', sa.Integer(), nullable=False),
    sa.Column('total_3pm', sa.Integer(), nullable=False),
    sa.Column('total_3pa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_player_game')
    )
    op.create_table('player_quarter_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_game_stat_id', sa.Integer(), nullable=False),
    sa.Column('quarter_number', sa.Integer(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('fg2m', sa.Integer(), nullable=False),
    sa.Column('fg2a', sa.Integer(), nullable=False),
    sa.Column('fg3m', sa.Integer(), nullable=False),
    sa.Column('fg3a', sa.Integer(), nullable=False),
    sa.CheckConstraint('quarter_number >= 1 AND quarter_number <= 4', name='check_quarter_number'),
    sa.ForeignKeyConstraint(['player_game_stat_id'], ['player_game_stats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_game_stat_id', 'quarter_number', name='uq_player_game_quarter')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_quarter_stats')
    op.drop_table('player_game_stats')
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('teams')
    # ### end Alembic commands ###
