"""Add playoff configuration model

Revision ID: c2ca55dc5329
Revises: 20a8f90c4c75
Create Date: 2025-07-28 13:43:07.423624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2ca55dc5329'
down_revision = '20a8f90c4c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playoff_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('num_rounds', sa.Integer(), nullable=False),
    sa.Column('bracket_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'is_active', name='unique_active_season_config')
    )
    op.drop_constraint('active_rosters_game_id_player_id_key', 'active_rosters', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('active_rosters_game_id_player_id_key', 'active_rosters', ['game_id', 'player_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('playoff_configs')
    # ### end Alembic commands ###
