"""add overtime support

Revision ID: e31c9e352add
Revises: fd0f8271073e
Create Date: 2025-07-01 12:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e31c9e352add"
down_revision = "fd0f8271073e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_states", schema=None) as batch_op:
        batch_op.drop_constraint("check_quarter_number", type_="check")
        batch_op.create_check_constraint("check_quarter_number", "current_quarter >= 1 AND current_quarter <= 6")

    with op.batch_alter_table("player_quarter_stats", schema=None) as batch_op:
        batch_op.drop_constraint("check_quarter_number", type_="check")
        batch_op.create_check_constraint("check_quarter_number", "quarter_number >= 1 AND quarter_number <= 6")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_states", schema=None) as batch_op:
        batch_op.drop_constraint("check_quarter_number", type_="check")
        batch_op.create_check_constraint("check_quarter_number", "current_quarter >= 1 AND current_quarter <= 4")

    with op.batch_alter_table("player_quarter_stats", schema=None) as batch_op:
        batch_op.drop_constraint("check_quarter_number", type_="check")
        batch_op.create_check_constraint("check_quarter_number", "quarter_number >= 1 AND quarter_number <= 4")
    # ### end Alembic commands ###
