"""add_is_playoff_game_to_games

Revision ID: f378ca14303a
Revises: 302e946efab0
Create Date: 2025-07-28 12:44:16.673666

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f378ca14303a"
down_revision = "302e946efab0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("is_playoff_game", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "is_playoff_game")
    # ### end Alembic commands ###
