name: Continuous Integration

on:
  push:
    branches-ignore: [main, master]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  # Quick validation for development branches
  quick-test:
    name: Quick Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          
      - name: Run linter
        run: |
          ruff check . --output-format=github
          
      - name: Run unit tests
        env:
          JWT_SECRET_KEY: test-secret-key-for-ci-environment-12345678
        run: |
          pytest tests/unit/ -v --tb=short
          
  # Docker build test (lighter than full PR validation)
  docker-build-test:
    name: Docker Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          docker build --target production -t basketball-stats:ci-test .